# Generated by Django 2.1.3 on 2018-12-02 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20181203_0450'),
        ('rounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('blogs', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='level_img', to='questions.Level')),
            ],
        ),
    ]
