# Generated by Django 2.1.3 on 2018-11-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=6, unique=True)),
                ('question_1', models.CharField(max_length=4444)),
                ('question_2', models.CharField(max_length=4444)),
                ('hint_1', models.CharField(blank=True, max_length=600, null=True)),
                ('hint_2', models.CharField(blank=True, max_length=600, null=True)),
                ('hint_3', models.CharField(blank=True, max_length=600, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
