# Generated by Django 2.1.3 on 2018-11-20 20:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=4444)),
                ('question_2', models.CharField(blank=True, max_length=4444, null=True)),
                ('hint_1', models.CharField(blank=True, max_length=600, null=True)),
                ('hint_2', models.CharField(blank=True, max_length=600, null=True)),
                ('hint_3', models.CharField(blank=True, max_length=600, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('maximum_time', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.Level')),
            ],
        ),
    ]
