# Generated by Django 2.1.3 on 2018-11-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='level',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
