# Generated by Django 2.1.3 on 2018-11-21 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='maximum_time',
        ),
        migrations.AddField(
            model_name='questions',
            name='time_in_hr',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='time_in_min',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(60)]),
            preserve_default=False,
        ),
    ]
