# Generated by Django 2.1.3 on 2018-11-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20181114_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_2',
            field=models.CharField(blank=True, max_length=4444, null=True),
        ),
    ]
