# Generated by Django 2.1.3 on 2018-11-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20181121_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='day',
            field=models.CharField(default='task-1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='title',
            field=models.CharField(default='task-a', max_length=30),
            preserve_default=False,
        ),
    ]
