# Generated by Django 2.1.3 on 2018-11-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20181124_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='day',
            field=models.DateTimeField(),
        ),
    ]
