# Generated by Django 2.1.3 on 2018-11-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20181124_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='event',
            field=models.CharField(choices=[('d1', 'Day-1'), ('d2', 'Day-2'), ('d3', 'Day-3'), ('d4', 'Day-4')], default='Day-1', max_length=10),
        ),
    ]
