# Generated by Django 2.1.3 on 2018-11-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_questions_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='event',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='Day-1', max_length=10),
        ),
    ]
