# Generated by Django 2.1.3 on 2018-12-04 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_levelforjudge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelforjudge',
            name='level',
        ),
        migrations.AddField(
            model_name='levelforjudge',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.Questions'),
        ),
    ]
