# Generated by Django 2.1.3 on 2018-12-04 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20181205_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelforjudge',
            name='question',
        ),
        migrations.AddField(
            model_name='levelforjudge',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='levelquestions', to='questions.Questions'),
        ),
    ]
