# Generated by Django 2.1.3 on 2018-12-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20181205_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='file',
            field=models.FileField(default='default', upload_to='question/'),
            preserve_default=False,
        ),
    ]
